METADATA_FILE = "C:/Users/xavid/Documents/uni/DADES/4t any/PSIV2/malaltia/CroppedPatches/metadata.csv"
CROPPED_PATCHES_DIR = "C:/Users/xavid/Documents/uni/DADES/4t any/PSIV2/malaltia/CroppedPatches/"
SAVE_MODEL_DIR = "C:/Users/xavid/Documents/GitHub/PSIV3_malaltia/autoencoder/models"
PLOT_LOSS_DIR = "C:/Users/xavid/Documents/GitHub/PSIV3_malaltia/autoencoder/plots"
SAVED_MODEL = "/fhome/mapsiv01/PSIV3_malaltia/autoencoder/models/model5_AUTOENCODER.pth"
ANNOTATED_PATCHES_DIR = "C:/Users/xavid/Documents/uni/DADES/4t any/PSIV2/malaltia/AnnotatedPatches/"
WINDOW_METADATA_FILE = "C:/Users/xavid/Documents/uni/DADES/4t any/PSIV2/malaltia/AnnotatedPatches/window_metadata.csv"